#!/usr/bin/env python3
r"""Stratified S' search on two ramified nonprincipal length-five bases.

The division syzygy is computed exhaustively.  Socle shifts are discarded
exactly (fiber2 puts phi in m), and an F_2-basis of the residual syzygy
quotient is derived rather than hard-coded.  Failure at each augmentation
basis vector is then an existential/ForAll formula over only the residual
bits.  Every parametrization is checked against the complete finite syzygy
set before any Hopf query runs.
"""

import argparse
import itertools
import sys
import time

from z3 import And, BitVec, ForAll, If, Not, Solver, is_true, sat, set_param, simplify

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from order4sat_f8ram_alpha2mu2_pinned_20260709 import MODELS as XY_MODELS
from order4sat_ramified_embdim2_len6_20260709 import PinCoproductResidue
from order4sat_ramified_gorenstein_len5_20260709 import (
    RamifiedGorensteinLen5, ring_gates as ring_gates_r5,
)
from order4sat_ramified_towers_20260709 import value
from order4sat_ramified_xy_gorenstein_len5_20260709 import (
    RamifiedXYGorensteinLen5, ring_gates as ring_gates_rxy,
)
from sprime_ramified_length4_six_20260709 import (
    in_kernel, module_div_eqs, sp_nonprincipal_holds,
)
from sprime_ramified_principal_depth5_stratified_20260709 import (
    T4_MULT, XY_MULT, t4_pins,
)
from s2check import build_blocks


def add_tuple(R, x, y):
    return tuple(R.add(a, b) for a, b in zip(x, y))


def tuple_key(x):
    return tuple(value(a) for a in x)


def residual_syzygy_basis(R, gens):
    """Return (socle, basis) and exhaustively gate Syz/Soc^q."""
    els, z = R.elements(), R.zero()
    q = len(gens)
    soc = [a for a in els if all(value(R.mul(a, g)) == value(z) for g in gens)]
    syz = []
    for coeffs in itertools.product(els, repeat=q):
        total = z
        for g, a in zip(gens, coeffs):
            total = R.add(total, R.mul(g, a))
        if value(total) == value(z):
            syz.append(coeffs)

    # Soc^q is the initial subgroup.  The quotient is expected to be an
    # elementary F_2-vector space; check that rather than assume it.
    span = {tuple_key(x): x for x in itertools.product(soc, repeat=q)}
    for x in syz:
        assert tuple_key(add_tuple(R, x, x)) in span, "Syz/Soc^q is not F2-linear"
    basis = []
    for x in syz:
        if tuple_key(x) in span:
            continue
        basis.append(x)
        old = list(span.values())
        for y in old:
            w = add_tuple(R, y, x)
            span[tuple_key(w)] = w
    assert set(span) == {tuple_key(x) for x in syz}
    assert len(span) == len(syz)
    print(f"  [syzygy gate] |Soc|={len(soc)}, |Syz|={len(syz)}, "
          f"dim_F2(Syz/Soc^q)={len(basis)} -> PASS", flush=True)
    return soc, basis


def scale_bit(bit, concrete, zero):
    if isinstance(concrete, tuple):
        return tuple(scale_bit(bit, a, z) for a, z in zip(concrete, zero))
    return If(bit == 1, concrete, zero)


def residual_span(R, basis):
    """All residual syzygies generated by the checked F2 basis."""
    q = len(basis[0]) if basis else 0
    out = [tuple(R.zero() for _ in range(q))]
    for h in basis:
        out += [add_tuple(R, x, h) for x in list(out)]
    return out


def fail_i_residual(R, phi, gens, basis, tag, i, unroll=False):
    q = len(gens)
    vecs = [[R.var(f"{tag}v{i}_{j}_{r}") for r in range(3)] for j in range(q)]
    division = And(*module_div_eqs(R, phi[i], vecs, gens))
    if unroll:
        shifts = residual_span(R, basis)
        misses = []
        for coordinate_shifts in itertools.product(shifts, repeat=3):
            shifted = [list(v) for v in vecs]
            for r, shift in enumerate(coordinate_shifts):
                for j in range(q):
                    shifted[j][r] = R.add(shifted[j][r], shift[j])
            misses.append(Not(And(*[in_kernel(R, phi, v) for v in shifted])))
        print(f"      [unroll] {len(misses)} residual division representatives", flush=True)
        return And(division, *misses)

    shifted = [list(v) for v in vecs]
    bits = []
    for r in range(3):
        for h, syzvec in enumerate(basis):
            bit = BitVec(f"{tag}lam_{i}_{r}_{h}", 1)
            bits.append(bit)
            for j in range(q):
                shifted[j][r] = R.add(
                    shifted[j][r], scale_bit(bit, syzvec[j], R.zero()))
    misses = Not(And(*[in_kernel(R, phi, v) for v in shifted]))
    return And(division, ForAll(bits, misses)) if bits else And(division, misses)


def solve(label, constraints, timeout):
    s = Solver()
    s.set("timeout", timeout * 1000)
    s.add(*constraints)
    t0 = time.monotonic()
    ans = s.check()
    print(f"    [{label}] -> {ans} ({time.monotonic()-t0:.2f}s)", flush=True)
    return ans


def run_model(base, gens, basis, fib, pins, label, timeout, unroll=False, only_i=(1,2,3)):
    print(f"  --- {label} ---", flush=True)
    R = PinCoproductResidue(base, pins)
    A, M, C, F, phi, _, _ = build_blocks(R, fib)
    core = A + M + C + F
    holds = sp_nonprincipal_holds(R, phi, gens, "np5")
    if solve("S1 axioms+fiber2+S'-HOLDS", core + [holds], timeout) != sat:
        raise RuntimeError("nonvacuity gate failed")
    out = []
    for i in only_i:
        failure = fail_i_residual(R, phi, gens, basis, "np5", i, unroll=unroll)
        out.append(solve(f"S2.{i} axioms+fiber2+S'-FAIL_i", core + [failure], timeout))
    return out


def run_ring(base, gens, gate, timeout, which_fibers, xy_model_names,
             unroll=False, only_i=(1,2,3)):
    print(f"===== S' NONPRINCIPAL DEPTH5 base {base.name} =====", flush=True)
    gate(base)
    mspan = set()
    for coeffs in itertools.product(base.elements(), repeat=len(gens)):
        z = base.zero()
        for g, a in zip(gens, coeffs):
            z = base.add(z, base.mul(g, a))
        mspan.add(value(z))
    m = {value(x) for x in base.elements() if is_true(simplify(base.lowzero(x)))}
    assert mspan == m
    _, basis = residual_syzygy_basis(base, gens)
    results = []
    if which_fibers in ("xy", "all"):
        for name in xy_model_names:
            pins = XY_MODELS[name]
            results.append((f"xy/{name}", run_model(
                base, gens, basis, XY_MULT, pins, f"xy/{name}", timeout,
                unroll=unroll, only_i=only_i)))
    if which_fibers in ("t4", "all"):
        for c1, c4 in itertools.product((0, 1), repeat=2):
            label = f"t4/c1={c1},c4={c4}"
            results.append((label, run_model(
                base, gens, basis, T4_MULT, t4_pins(c1, c4), label, timeout,
                unroll=unroll, only_i=only_i)))
    print("  SUMMARY", flush=True)
    for label, vals in results:
        print(f"    {label}: {','.join(map(str, vals))}", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ring", choices=("R5", "Rxy", "all"), default="R5")
    ap.add_argument("--fibers", choices=("xy", "t4", "all"), default="xy")
    ap.add_argument("--timeout", type=int, default=1800)
    ap.add_argument("--xy-models", nargs="+", choices=tuple(XY_MODELS),
                    default=tuple(XY_MODELS))
    ap.add_argument("--unroll", action="store_true",
                    help="expand the finite residual universal quantifier")
    ap.add_argument("--only-i", nargs="+", type=int, choices=(1,2,3), default=(1,2,3))
    args = ap.parse_args()
    set_param("parallel.enable", True)
    if args.ring in ("R5", "all"):
        R = RamifiedGorensteinLen5()
        run_ring(R, [R.concrete(0,1,0), R.concrete(0,0,1)],
                 ring_gates_r5, args.timeout, args.fibers, args.xy_models,
                 unroll=args.unroll, only_i=args.only_i)
    if args.ring in ("Rxy", "all"):
        R = RamifiedXYGorensteinLen5()
        run_ring(R, [R.concrete(0,1,0,0), R.concrete(0,0,0,1)],
                 ring_gates_rxy, args.timeout, args.fibers, args.xy_models,
                 unroll=args.unroll, only_i=args.only_i)
    print("DONE sprime_ramified_nonprincipal_depth5_stratified_20260709", flush=True)


if __name__ == "__main__":
    main()
