#!/usr/bin/env python3
"""Exact tangent-cone audit for ``m2/universal_local_rank4.m2``.

This is deliberately dependency-free.  It reconstructs the 45-variable
universal bialgebra chart, truncates at deformation order two, and works over
F_2 with bit-packed linear algebra.  Two coefficient modes are supported:

* ``f2``: the ordinary m-adic tangent cone in equal characteristic two;
* ``mixed``: the (2,m)-adic tangent cone over Z_(2), with an extra variable
  ``tau = in(2)``.

For generators f_a = l_a + q_a + ..., the degree-two initial ideal is not
generated just by the q_a.  After quotienting by the linear equations l_a,
it is generated by the degree-two initial forms of all constant relations
among the l_a.  In mixed characteristic these are formed over the integers
*before* taking the initial form, so that 2-adic carries are retained.

The output gives exact ranks and a deterministic SHA-256 certificate for each
target membership computation.  The certificate payload (enabled by
``--certificates``) records bit-packed relation and division witnesses.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from itertools import combinations_with_replacement
from typing import Dict, Iterable, List, Sequence, Tuple


Mon = Tuple[int, ...]
Poly = Dict[Mon, int]

N_MUL = 18
N_COP = 27
N_VARS = N_MUL + N_COP
MAX_DEGREE = 3


def clean(p: Poly) -> Poly:
    return {m: c for m, c in p.items() if c}


def add(p: Poly, q: Poly, scale: int = 1) -> Poly:
    out = dict(p)
    for m, c in q.items():
        out[m] = out.get(m, 0) + scale * c
        if out[m] == 0:
            del out[m]
    return out


def mul(p: Poly, q: Poly) -> Poly:
    out: Poly = {}
    for a, ca in p.items():
        for b, cb in q.items():
            m = tuple(sorted(a + b))
            if len(m) <= MAX_DEGREE:
                out[m] = out.get(m, 0) + ca * cb
    return clean(out)


def const(c: int) -> Poly:
    return {} if c == 0 else {(): c}


def var(i: int) -> Poly:
    return {(i,): 1}


ZERO: Poly = {}
ONE: Poly = {(): 1}


def vadd(u: Sequence[Poly], v: Sequence[Poly], scale: int = 1) -> List[Poly]:
    return [add(a, b, scale) for a, b in zip(u, v)]


def vscale(p: Poly, u: Sequence[Poly]) -> List[Poly]:
    return [mul(p, a) for a in u]


def basis(i: int, n: int = 4) -> List[Poly]:
    return [ONE if j == i else ZERO for j in range(n)]


def pair_position(a: int, b: int) -> int:
    u, v = min(a, b), max(a, b)
    if u == 1:
        return v - 1
    if u == 2:
        return v + 1
    return 5


def mvar(i: int, j: int, r: int) -> Poly:
    return var(3 * pair_position(i, j) + r - 1)


def cvar(i: int, j: int, k: int) -> Poly:
    return var(N_MUL + 9 * (i - 1) + 3 * (j - 1) + k - 1)


def idx2(a: int, b: int) -> int:
    return 4 * a + b


def idx3(a: int, b: int, c: int) -> int:
    return 16 * a + 4 * b + c


@dataclass
class Chart:
    name: str
    equations_z: List[Poly]
    equations_f2: List[Poly]
    targets_z: List[Poly]
    phi_z: List[List[Poly]]


def mod2_poly(p: Poly) -> Poly:
    return {m: 1 for m, c in p.items() if c & 1}


def unique_polys(polys: Iterable[Poly], mode: str) -> List[Poly]:
    out: List[Poly] = []
    seen = set()
    for p0 in polys:
        p = mod2_poly(p0) if mode == "f2" else clean(p0)
        if not p:
            continue
        key = tuple(sorted(p.items()))
        if key not in seen:
            seen.add(key)
            out.append(p)
    return out


def build_chart(branch: int) -> Chart:
    if branch not in range(4):
        raise ValueError(branch)
    is_t4 = branch >= 2
    c1bit = 0
    c4bit = branch - 2 if is_t4 else 0
    name = ("a2a2", "W2F", "t4_00", "t4_01")[branch]
    fiber_mul = {(1, 1, 2), (1, 2, 3)} if is_t4 else {(1, 2, 3)}

    def pin_cop(i: int, j: int, k: int) -> int:
        if not is_t4:
            if (i, j, k) in {(3, 1, 2), (3, 2, 1)}:
                return 1
            if branch == 1 and (i, j, k) == (2, 1, 1):
                return 1
            return 0
        if i == 1:
            if (j, k) in {(1, 2), (2, 1), (2, 3), (3, 2)}:
                return c1bit
            if (j, k) == (2, 2):
                return c4bit
            return 0
        if i == 2:
            return 0
        if (j, k) in {(1, 2), (2, 1)}:
            return 1
        if (j, k) in {(2, 3), (3, 2)}:
            return c1bit
        return 0

    def mc(i: int, j: int, r: int) -> Poly:
        return add(const(int((min(i, j), max(i, j), r) in fiber_mul)), mvar(i, j, r))

    def cc(i: int, j: int, k: int) -> Poly:
        return add(const(pin_cop(i, j, k)), cvar(i, j, k))

    stab = {}
    for a in range(4):
        for b in range(4):
            if a == 0:
                stab[a, b] = basis(b)
            elif b == 0:
                stab[a, b] = basis(a)
            else:
                stab[a, b] = [ZERO, mc(a, b, 1), mc(a, b, 2), mc(a, b, 3)]

    delta: List[List[Poly]] = []
    delta.append([ONE if t == 0 else ZERO for t in range(16)])
    for i in range(1, 4):
        v = [ZERO for _ in range(16)]
        v[idx2(i, 0)] = ONE
        v[idx2(0, i)] = ONE
        for j in range(1, 4):
            for k in range(1, 4):
                v[idx2(j, k)] = cc(i, j, k)
        delta.append(v)

    def mula(u: Sequence[Poly], v: Sequence[Poly]) -> List[Poly]:
        out = [ZERO for _ in range(4)]
        for i in range(4):
            for j in range(4):
                uv = mul(u[i], v[j])
                if not uv:
                    continue
                for r in range(4):
                    out[r] = add(out[r], mul(uv, stab[i, j][r]))
        return out

    def dofvec(v: Sequence[Poly]) -> List[Poly]:
        out = [ZERO for _ in range(16)]
        for r in range(4):
            if not v[r]:
                continue
            for t in range(16):
                out[t] = add(out[t], mul(v[r], delta[r][t]))
        return out

    def mult2(u: Sequence[Poly], v: Sequence[Poly]) -> List[Poly]:
        out = [ZERO for _ in range(16)]
        for a in range(4):
            for b in range(4):
                ua = u[idx2(a, b)]
                if not ua:
                    continue
                for aa in range(4):
                    for bb in range(4):
                        uv = mul(ua, v[idx2(aa, bb)])
                        if not uv:
                            continue
                        for r in range(4):
                            for s in range(4):
                                term = mul(uv, mul(stab[a, aa][r], stab[b, bb][s]))
                                out[idx2(r, s)] = add(out[idx2(r, s)], term)
        return out

    assoc_raw: List[Poly] = []
    for i in range(1, 4):
        for j in range(1, 4):
            for k in range(1, 4):
                left = mula(stab[i, j], basis(k))
                right = mula(basis(i), stab[j, k])
                for r in range(1, 4):
                    assoc_raw.append(add(left[r], right[r], -1))

    compat_raw: List[Poly] = []
    for i in range(1, 4):
        for j in range(i, 4):
            left = dofvec(stab[i, j])
            right = mult2(delta[i], delta[j])
            for r in range(1, 4):
                for s in range(1, 4):
                    compat_raw.append(add(left[idx2(r, s)], right[idx2(r, s)], -1))

    coassoc_raw: List[Poly] = []
    for i in range(1, 4):
        left = [ZERO for _ in range(64)]
        right = [ZERO for _ in range(64)]
        for r in range(4):
            for s in range(4):
                u = delta[i][idx2(r, s)]
                if not u:
                    continue
                for a in range(4):
                    for b in range(4):
                        left[idx3(a, b, s)] = add(
                            left[idx3(a, b, s)], mul(u, delta[r][idx2(a, b)])
                        )
                for b in range(4):
                    for c in range(4):
                        right[idx3(r, b, c)] = add(
                            right[idx3(r, b, c)], mul(u, delta[s][idx2(b, c)])
                        )
        for a in range(1, 4):
            for b in range(1, 4):
                for c in range(1, 4):
                    coassoc_raw.append(add(left[idx3(a, b, c)], right[idx3(a, b, c)], -1))

    phi: List[List[Poly]] = [basis(0)]
    for i in range(1, 4):
        out = [ZERO for _ in range(4)]
        for j in range(4):
            for k in range(4):
                u = delta[i][idx2(j, k)]
                if not u:
                    continue
                for r in range(4):
                    out[r] = add(out[r], mul(u, stab[j, k][r]))
        phi.append(out)

    p4: List[List[Poly]] = []
    for i in range(1, 4):
        out = [ZERO for _ in range(4)]
        for r in range(1, 4):
            if not phi[i][r]:
                continue
            for s in range(1, 4):
                out[s] = add(out[s], mul(phi[i][r], phi[r][s]))
        p4.append(out)

    assoc_z = unique_polys(assoc_raw, "mixed")
    compat_z = unique_polys(compat_raw, "mixed")
    coassoc_z = unique_polys(coassoc_raw, "mixed")
    equations_z = unique_polys(assoc_z + compat_z + coassoc_z, "mixed")
    assoc_2 = unique_polys(assoc_raw, "f2")
    compat_2 = unique_polys(compat_raw, "f2")
    coassoc_2 = unique_polys(coassoc_raw, "f2")
    equations_f2 = unique_polys(assoc_2 + compat_2 + coassoc_2, "f2")
    targets_z = [p4[i][s] for i in range(3) for s in range(1, 4)]
    return Chart(name, equations_z, equations_f2, targets_z, phi)


def v2(n: int) -> int:
    if n == 0:
        raise ValueError("v2(0)")
    n = abs(n)
    out = 0
    while n % 2 == 0:
        n //= 2
        out += 1
    return out


def homogeneous_layer(p: Poly, degree: int, mode: str) -> Poly:
    out: Poly = {}
    tau = N_VARS
    for mon, c in p.items():
        if not c:
            continue
        if mode == "f2":
            if len(mon) == degree and (c & 1):
                out[mon] = out.get(mon, 0) ^ 1
        else:
            valuation = v2(c)
            if len(mon) + valuation == degree:
                lifted = tuple(sorted(mon + (tau,) * valuation))
                out[lifted] = out.get(lifted, 0) ^ 1
    return {m: 1 for m, c in out.items() if c}


def monomials(nvars: int, degree: int) -> List[Mon]:
    if degree == 1:
        return [(i,) for i in range(nvars)]
    return list(combinations_with_replacement(range(nvars), degree))


def poly_mask(p: Poly, lookup: Dict[Mon, int]) -> int:
    out = 0
    for m, c in p.items():
        if c & 1:
            out ^= 1 << lookup[m]
    return out


def xor_polys(polys: Sequence[Poly], selector: int) -> Poly:
    out: Poly = {}
    i = 0
    while selector:
        low = selector & -selector
        i = low.bit_length() - 1
        out = add(out, polys[i])
        selector ^= low
    return out


def exact_sum(polys: Sequence[Poly], selector: int) -> Poly:
    out: Poly = {}
    while selector:
        low = selector & -selector
        i = low.bit_length() - 1
        out = add(out, polys[i])
        selector ^= low
    return out


def echelon_with_combos(rows: Sequence[int]) -> Tuple[Dict[int, Tuple[int, int]], List[int]]:
    """Return a reduced pivot dictionary and a basis of row relations."""
    piv: Dict[int, Tuple[int, int]] = {}
    kernels: List[int] = []
    for i, row0 in enumerate(rows):
        row, combo = row0, 1 << i
        while row:
            p = row.bit_length() - 1
            if p not in piv:
                break
            row ^= piv[p][0]
            combo ^= piv[p][1]
        if not row:
            kernels.append(combo)
            continue
        p = row.bit_length() - 1
        for q, (oldrow, oldcombo) in list(piv.items()):
            if (oldrow >> p) & 1:
                piv[q] = (oldrow ^ row, oldcombo ^ combo)
        piv[p] = (row, combo)
    # The insertion loop gives row echelon form.  Clear all lower pivot
    # columns as well, so each relation is x_p plus free variables only.
    ordered = sorted(piv)
    for p in ordered:
        row, combo = piv[p]
        for q in reversed([q for q in ordered if q < p]):
            if (row >> q) & 1:
                row ^= piv[q][0]
                combo ^= piv[q][1]
        piv[p] = (row, combo)
    return piv, kernels


def insert_basis(
    piv: Dict[int, Tuple[int, int]], row0: int, combo0: int
) -> bool:
    row, combo = row0, combo0
    while row:
        p = row.bit_length() - 1
        if p not in piv:
            piv[p] = (row, combo)
            return True
        row ^= piv[p][0]
        combo ^= piv[p][1]
    return False


def insert_plain(piv: Dict[int, int], row0: int) -> bool:
    row = row0
    while row:
        p = row.bit_length() - 1
        if p not in piv:
            piv[p] = row
            return True
        row ^= piv[p]
    return False


def reduce_plain(piv: Dict[int, int], row0: int) -> int:
    row = row0
    while row:
        p = row.bit_length() - 1
        if p not in piv:
            return row
        row ^= piv[p]
    return 0


def solve_basis(piv: Dict[int, Tuple[int, int]], row0: int) -> Tuple[bool, int]:
    row, combo = row0, 0
    while row:
        p = row.bit_length() - 1
        if p not in piv:
            return False, 0
        row ^= piv[p][0]
        combo ^= piv[p][1]
    return True, combo


def bit_indices(mask: int) -> Iterable[int]:
    while mask:
        low = mask & -mask
        yield low.bit_length() - 1
        mask ^= low


def multiply_linear_masks(a: int, b: int, quad_lookup: Dict[Mon, int]) -> int:
    out = 0
    for i in bit_indices(a):
        for j in bit_indices(b):
            out ^= 1 << quad_lookup[tuple(sorted((i, j)))]
    return out


def audit_chart(chart: Chart, mode: str, emit_certificates: bool) -> dict:
    equations = chart.equations_f2 if mode == "f2" else chart.equations_z
    nvars = N_VARS if mode == "f2" else N_VARS + 1
    linear_mons = monomials(nvars, 1)
    linear_lookup = {m: i for i, m in enumerate(linear_mons)}
    linear_rows = [poly_mask(homogeneous_layer(f, 1, mode), linear_lookup) for f in equations]
    linear_piv, kernel = echelon_with_combos(linear_rows)
    pivot_vars = set(linear_piv)
    free_vars = [i for i in range(nvars) if i not in pivot_vars]
    free_pos = {v: i for i, v in enumerate(free_vars)}

    # RREF relations have pivot x_p and free-variable tails only.
    var_image: List[int] = [0] * nvars
    for v in free_vars:
        var_image[v] = 1 << free_pos[v]
    for p, (row, _) in linear_piv.items():
        image = 0
        for v in bit_indices(row ^ (1 << p)):
            if v not in free_pos:
                raise AssertionError("linear basis is not reduced")
            image ^= 1 << free_pos[v]
        var_image[p] = image

    parameter_names = []
    for i, j in ((1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)):
        for r in range(1, 4):
            parameter_names.append(f"m{i}{j}_{r}")
    for i in range(1, 4):
        for j in range(1, 4):
            for k in range(1, 4):
                parameter_names.append(f"c{i}{j}{k}")
    if mode == "mixed":
        parameter_names.append("tau")

    def reduce_linear(p: Poly) -> int:
        layer = homogeneous_layer(p, 1, mode)
        out = 0
        for mon, c in layer.items():
            if c & 1:
                out ^= var_image[mon[0]]
        return out

    def show_free_linear(mask: int) -> str:
        names = [parameter_names[free_vars[i]] for i in bit_indices(mask)]
        return "0" if not names else "+".join(names)

    doubling_matrix = []
    for r in range(1, 4):
        doubling_matrix.append([
            show_free_linear(reduce_linear(chart.phi_z[i][r]))
            for i in range(1, 4)
        ])

    free_quad_mons = monomials(len(free_vars), 2)
    free_quad_lookup = {m: i for i, m in enumerate(free_quad_mons)}
    ambient_quad_mons = monomials(nvars, 2)
    ambient_quad_lookup = {m: i for i, m in enumerate(ambient_quad_mons)}

    def reduce_quad(p: Poly) -> int:
        out = 0
        for mon, c in p.items():
            if not (c & 1):
                continue
            if len(mon) != 2:
                raise AssertionError(mon)
            out ^= multiply_linear_masks(var_image[mon[0]], var_image[mon[1]], free_quad_lookup)
        return out

    def divide_ambient_quad_by_linear(initial_mask: int) -> Tuple[int, Dict[int, int]]:
        """Divide a quadratic by the RREF linear equations, with witness."""
        current = initial_mask
        multipliers: Dict[int, int] = {}
        while True:
            chosen = None
            for qindex in bit_indices(current):
                a, b = ambient_quad_mons[qindex]
                candidates = [v for v in (a, b) if v in pivot_vars]
                if candidates:
                    p = max(candidates)
                    other = b if a == p else a
                    chosen = (p, other)
                    break
            if chosen is None:
                break
            p, other = chosen
            lrow = linear_piv[p][0]
            current ^= multiply_linear_masks(1 << other, lrow, ambient_quad_lookup)
            multipliers[p] = multipliers.get(p, 0) ^ (1 << other)
            if not multipliers[p]:
                del multipliers[p]
        return current, multipliers

    relation_quadrics: List[int] = []
    relation_sources: List[int] = []
    for ker in kernel:
        summed = exact_sum(equations, ker)
        q = homogeneous_layer(summed, 2, mode)
        rq = reduce_quad(q)
        if rq:
            relation_quadrics.append(rq)
            relation_sources.append(ker)

    q_piv: Dict[int, Tuple[int, int]] = {}
    for i, row in enumerate(relation_quadrics):
        insert_basis(q_piv, row, 1 << i)

    target_results = []
    cert_digest = hashlib.sha256()
    for target_index, target in enumerate(chart.targets_z):
        t2 = homogeneous_layer(target, 2, mode)
        rt = reduce_quad(t2)
        member, combo = solve_basis(q_piv, rt)
        selected_sources = [relation_sources[i] for i in bit_indices(combo)] if member else []
        ambient_t2 = poly_mask(t2, ambient_quad_lookup)
        linear_remainder, linear_multipliers = divide_ambient_quad_by_linear(ambient_t2)
        if combo == 0:
            assert((linear_remainder == 0) == (rt == 0))
        linear_certificate = [
            {
                "pivot_variable": parameter_names[p],
                "multiplier_linear_mask_hex": hex(multiplier),
                "linear_equation_selector_hex": hex(linear_piv[p][1]),
            }
            for p, multiplier in sorted(linear_multipliers.items())
        ] if combo == 0 and linear_remainder == 0 else []
        payload = {
            "target": target_index,
            "initial_mask_hex": hex(ambient_t2),
            "reduced_mask_hex": hex(rt),
            "member": member,
            "quadratic_relation_selector_hex": hex(combo),
            "constant_linear_relation_sources_hex": [hex(x) for x in selected_sources],
            "linear_division_certificate": linear_certificate,
        }
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        cert_digest.update(encoded)
        target_results.append(payload if emit_certificates else {
            "target": target_index,
            "reduced_nonzero": bool(rt),
            "member": member,
            "relations_used": combo.bit_count(),
        })

    return {
        "chart": chart.name,
        "mode": mode,
        "equations": len(equations),
        "ambient_linear_variables": nvars,
        "linear_rank": len(linear_piv),
        "tangent_dimension": len(free_vars),
        "constant_linear_relation_dimension": len(kernel),
        "nonzero_quadratic_relation_rows": len(relation_quadrics),
        "quadratic_relation_rank_on_tangent_space": len(q_piv),
        "tangent_quadratic_dimension_before_relations": len(free_quad_mons),
        "tangent_quadratic_dimension_after_relations": len(free_quad_mons) - len(q_piv),
        "free_variables": free_vars,
        "first_order_doubling_matrix_rows": doubling_matrix,
        "targets": target_results,
        "certificate_sha256": cert_digest.hexdigest(),
    }


def audit_f2_jet3(chart: Chart) -> dict:
    """Test target membership in I + m^4 over F_2 by exact linear algebra."""
    equations = chart.equations_f2
    jet_mons = (
        monomials(N_VARS, 1)
        + monomials(N_VARS, 2)
        + monomials(N_VARS, 3)
    )
    jet_lookup = {m: i for i, m in enumerate(jet_mons)}
    multipliers = [()] + monomials(N_VARS, 1) + monomials(N_VARS, 2)

    def multiplied_mask(f: Poly, multiplier: Mon) -> int:
        out = 0
        for m, c in f.items():
            if not (c & 1) or len(m) + len(multiplier) > 3:
                continue
            mm = tuple(sorted(m + multiplier))
            if mm:
                out ^= 1 << jet_lookup[mm]
        return out

    piv: Dict[int, int] = {}
    nonzero_rows = 0
    for f in equations:
        for multiplier in multipliers:
            row = multiplied_mask(f, multiplier)
            if row:
                nonzero_rows += 1
                insert_plain(piv, row)

    targets = []
    digest = hashlib.sha256()
    for i, target in enumerate(chart.targets_z):
        row = multiplied_mask(mod2_poly(target), ())
        remainder = reduce_plain(piv, row)
        item = {
            "target": i,
            "member_mod_m4": remainder == 0,
            "remainder_sha256": hashlib.sha256(
                remainder.to_bytes(max(1, (remainder.bit_length() + 7) // 8), "little")
            ).hexdigest(),
        }
        digest.update(json.dumps(item, sort_keys=True).encode())
        targets.append(item)
    return {
        "jet3_monomial_columns": len(jet_mons),
        "jet3_candidate_rows": len(equations) * len(multipliers),
        "jet3_nonzero_rows": nonzero_rows,
        "jet3_ideal_rank": len(piv),
        "jet3_quotient_dimension": len(jet_mons) - len(piv),
        "jet3_targets": targets,
        "jet3_certificate_sha256": digest.hexdigest(),
    }


def audit_filtered_degree3(chart: Chart, mode: str) -> dict:
    """Compute gr(I) through degree three, retaining mixed-char carries."""
    equations = chart.equations_f2 if mode == "f2" else chart.equations_z
    nvars = N_VARS if mode == "f2" else N_VARS + 1
    linear_mons = monomials(nvars, 1)
    linear_lookup = {m: i for i, m in enumerate(linear_mons)}
    quad_mons = monomials(nvars, 2)
    quad_lookup = {m: i for i, m in enumerate(quad_mons)}
    cubic_mons = monomials(nvars, 3)
    cubic_lookup = {m: i for i, m in enumerate(cubic_mons)}
    parameter_names = []
    for i, j in ((1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)):
        for r in range(1, 4):
            parameter_names.append(f"m{i}{j}_{r}")
    for i in range(1, 4):
        for j in range(1, 4):
            for k in range(1, 4):
                parameter_names.append(f"c{i}{j}{k}")
    if mode == "mixed":
        parameter_names.append("tau")

    def show_cubic_mask(mask: int) -> List[str]:
        return [
            "*".join(parameter_names[v] for v in cubic_mons[i])
            for i in bit_indices(mask)
        ]

    def layer_mask(p: Poly, degree: int, lookup: Dict[Mon, int]) -> int:
        return poly_mask(homogeneous_layer(p, degree, mode), lookup)

    linear_rows = [layer_mask(f, 1, linear_lookup) for f in equations]
    linear_piv, linear_kernel = echelon_with_combos(linear_rows)

    def actual_parameter(v: int) -> Poly:
        if mode == "mixed" and v == N_VARS:
            return const(2)
        return var(v)

    # Representatives spanning (I cap q^2)/(I cap q^3): parameter
    # multiples of a basis of gr(I)_1, plus lifted constant syzygies.
    e2: List[Poly] = []
    for _, (_, selector) in sorted(linear_piv.items()):
        g = exact_sum(equations, selector)
        for v in range(nvars):
            e2.append(mul(actual_parameter(v), g))
    for selector in linear_kernel:
        e2.append(exact_sum(equations, selector))

    e2_rows = [layer_mask(f, 2, quad_lookup) for f in e2]
    degree2_piv, degree2_kernel = echelon_with_combos(e2_rows)

    def quad_times_variable(row: int, v: int) -> int:
        out = 0
        for qi in bit_indices(row):
            mon = tuple(sorted(quad_mons[qi] + (v,)))
            out ^= 1 << cubic_lookup[mon]
        return out

    cubic_rows: List[int] = []
    # Parameter multiples of gr(I)_2.
    for row, _ in degree2_piv.values():
        for v in range(nvars):
            cubic_rows.append(quad_times_variable(row, v))
    # Degree-three carries/S-polynomials from every relation in degree two.
    for selector in degree2_kernel:
        residual = exact_sum(e2, selector)
        cubic_rows.append(layer_mask(residual, 3, cubic_lookup))

    cubic_piv: Dict[int, int] = {}
    nonzero_cubic_rows = 0
    for row in cubic_rows:
        if row:
            nonzero_cubic_rows += 1
            insert_plain(cubic_piv, row)

    # RREF variable images for the canonical quadratic cancellation.
    pivot_vars = set(linear_piv)

    def divide_quad(initial_mask: int) -> Tuple[int, Dict[int, int]]:
        current = initial_mask
        multipliers: Dict[int, int] = {}
        while True:
            chosen = None
            for qindex in bit_indices(current):
                a, b = quad_mons[qindex]
                candidates = [v for v in (a, b) if v in pivot_vars]
                if candidates:
                    p = max(candidates)
                    other = b if a == p else a
                    chosen = p, other
                    break
            if chosen is None:
                break
            p, other = chosen
            current ^= multiply_linear_masks(1 << other, linear_piv[p][0], quad_lookup)
            multipliers[p] = multipliers.get(p, 0) ^ (1 << other)
            if not multipliers[p]:
                del multipliers[p]
        return current, multipliers

    target_results = []
    digest = hashlib.sha256()
    for target_index, target in enumerate(chart.targets_z):
        t2mask = layer_mask(target, 2, quad_lookup)
        qrem, multipliers = divide_quad(t2mask)
        if qrem:
            raise AssertionError("quadratic target did not reduce by linear equations")
        residual = dict(target)
        for p, hmask in multipliers.items():
            h: Poly = {}
            for v in bit_indices(hmask):
                h = add(h, actual_parameter(v))
            gp = exact_sum(equations, linear_piv[p][1])
            residual = add(residual, mul(h, gp))
        if layer_mask(residual, 1, linear_lookup) != 0:
            raise AssertionError("target cancellation left a linear term")
        if layer_mask(residual, 2, quad_lookup) != 0:
            raise AssertionError("target cancellation left a quadratic term")
        r3 = layer_mask(residual, 3, cubic_lookup)
        remainder = reduce_plain(cubic_piv, r3)
        dual = 0
        if remainder:
            free_coordinate = remainder.bit_length() - 1
            if free_coordinate in cubic_piv:
                raise AssertionError("remainder pivot unexpectedly reducible")
            dual = 1 << free_coordinate
            for p in sorted(cubic_piv):
                lower = cubic_piv[p] ^ (1 << p)
                if (lower & dual).bit_count() & 1:
                    dual |= 1 << p
            if any((row & dual).bit_count() & 1 for row in cubic_piv.values()):
                raise AssertionError("dual obstruction does not annihilate ideal")
            if not ((r3 & dual).bit_count() & 1):
                raise AssertionError("dual obstruction does not detect target")
        dual_bytes = dual.to_bytes(max(1, (dual.bit_length() + 7) // 8), "little")
        item = {
            "target": target_index,
            "member_through_degree3": remainder == 0,
            "cubic_initial_nonzero_after_canonical_quadratic_cancellation": bool(r3),
            "cubic_remainder_sha256": hashlib.sha256(
                remainder.to_bytes(max(1, (remainder.bit_length() + 7) // 8), "little")
            ).hexdigest(),
            "cubic_remainder_terms": show_cubic_mask(remainder),
            "dual_obstruction_support_size": dual.bit_count(),
            "dual_obstruction_sha256": hashlib.sha256(dual_bytes).hexdigest(),
        }
        digest.update(json.dumps(item, sort_keys=True).encode())
        target_results.append(item)
    return {
        "filtered_degree2_spanning_elements": len(e2),
        "filtered_degree2_rank": len(degree2_piv),
        "filtered_degree2_relation_dimension": len(degree2_kernel),
        "filtered_degree3_candidate_rows": len(cubic_rows),
        "filtered_degree3_nonzero_rows": nonzero_cubic_rows,
        "filtered_degree3_rank": len(cubic_piv),
        "filtered_degree3_ambient_dimension": len(cubic_mons),
        "filtered_degree3_targets": target_results,
        "filtered_degree3_certificate_sha256": digest.hexdigest(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("f2", "mixed", "both"), default="both")
    parser.add_argument("--certificates", action="store_true")
    parser.add_argument(
        "--jet3", action="store_true",
        help="also test exact F2 membership modulo m^4 (can take longer)",
    )
    args = parser.parse_args()
    modes = ("f2", "mixed") if args.mode == "both" else (args.mode,)
    reports = []
    for branch in range(4):
        chart = build_chart(branch)
        for mode in modes:
            report = audit_chart(chart, mode, args.certificates)
            if args.jet3:
                report.update(audit_filtered_degree3(chart, mode))
                if mode == "f2":
                    direct = audit_f2_jet3(chart)
                    report.update(direct)
                    if not all(t["member_mod_m4"] for t in direct["jet3_targets"]):
                        raise AssertionError("direct F2 jet audit found an open target")
            reports.append(report)
    print(json.dumps(reports, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
