#!/usr/bin/env python3
"""Concrete 256-element tables for two missing quadratic CI types.

The rings are

    Rsp = Z[x,y]/(xy, x^4+y^4, x^4-2),
    Rirr = Z[x,y]/(x^2+xy+y^2, x^4, x^3*y-2).

Both have residue field F_2, characteristic four, length eight, Hilbert
function (1,2,2,2,1), and one-dimensional socle generated by 2.  Their
associated-graded quadratic relations are respectively ``xy`` and
``x^2+xy+y^2``.

This module deliberately contains no solver code.  It constructs all 256^2
addition and multiplication entries and compares every multiplication entry
with a second evaluator that reduces monomials directly from the displayed
presentations.  The resulting tables are then used as an independent gate by
``search_rank4_length8_other_ci_bool_20260711.py``.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Dict, Iterable, Mapping, Sequence, Tuple


Coord = Tuple[int, ...]
Products = Mapping[Tuple[int, int], Mapping[int, int]]
Reduction = Dict[int, int]


@dataclass(frozen=True)
class RingSpec:
    key: str
    name: str
    basis: Tuple[str, ...]
    widths: Tuple[int, ...]
    degrees: Tuple[int, ...]
    products: Products
    quadratic_kernel: Tuple[int, int, int]

    @property
    def cardinality(self) -> int:
        return 1 << sum(self.widths)


def ring_spec(key: str) -> RingSpec:
    if key == "split":
        # Coordinates: 1 (mod 4), followed by x,y,x^2,y^2,x^3,y^3 (mod 2).
        # The quartic socle is x^4=-y^4=2.
        return RingSpec(
            key="split",
            name="Rsp=Z[x,y]/(xy,x^4+y^4,x^4-2)",
            basis=("1", "x", "y", "x2", "y2", "x3", "y3"),
            widths=(2, 1, 1, 1, 1, 1, 1),
            degrees=(0, 1, 1, 2, 2, 3, 3),
            products={
                (1, 1): {3: 1},
                (2, 2): {4: 1},
                (1, 3): {5: 1},
                (2, 4): {6: 1},
                (1, 5): {0: 2},
                (3, 3): {0: 2},
                (2, 6): {0: 2},
                (4, 4): {0: 2},
            },
            quadratic_kernel=(0, 1, 0),
        )
    if key == "irreducible":
        # Coordinates: 1 (mod 4), followed by
        # x,y,x^2,xy,x^3,x^2y (mod 2).  The quartic socle is x^3y=2.
        return RingSpec(
            key="irreducible",
            name="Rirr=Z[x,y]/(x^2+xy+y^2,x^4,x^3y-2)",
            basis=("1", "x", "y", "x2", "xy", "x3", "x2y"),
            widths=(2, 1, 1, 1, 1, 1, 1),
            degrees=(0, 1, 1, 2, 2, 3, 3),
            products={
                (1, 1): {3: 1},
                (1, 2): {4: 1},
                (2, 2): {3: 1, 4: 1},
                (1, 3): {5: 1},
                (1, 4): {6: 1},
                (2, 3): {6: 1},
                (2, 4): {5: 1, 6: 1},
                (1, 6): {0: 2},
                (2, 5): {0: 2},
                (2, 6): {0: 2},
                (3, 4): {0: 2},
                (4, 4): {0: 2},
            },
            quadratic_kernel=(1, 1, 1),
        )
    raise ValueError(key)


def zero(spec: RingSpec) -> Coord:
    return (0,) * len(spec.widths)


def one(spec: RingSpec) -> Coord:
    return (1,) + (0,) * (len(spec.widths) - 1)


def two(spec: RingSpec) -> Coord:
    return (2,) + (0,) * (len(spec.widths) - 1)


def add(spec: RingSpec, left: Coord, right: Coord) -> Coord:
    return tuple((a + b) % (1 << width)
                 for a, b, width in zip(left, right, spec.widths))


def neg(spec: RingSpec, value: Coord) -> Coord:
    return tuple((-a) % (1 << width) for a, width in zip(value, spec.widths))


def scale(spec: RingSpec, coefficient: int, value: Coord) -> Coord:
    return tuple((coefficient * a) % (1 << width)
                 for a, width in zip(value, spec.widths))


def mul(spec: RingSpec, left: Coord, right: Coord) -> Coord:
    """Multiplication from the explicit structure-constant table."""
    products: Dict[Tuple[int, int], Dict[int, int]] = {
        tuple(sorted(pair)): dict(outputs) for pair, outputs in spec.products.items()
    }
    for i in range(len(spec.widths)):
        products[(0, i)] = {i: 1}
    out = [0] * len(spec.widths)
    for i, a in enumerate(left):
        for j, b in enumerate(right):
            for target, coefficient in products.get(tuple(sorted((i, j))), {}).items():
                out[target] += a * b * coefficient
    return tuple(value % (1 << width) for value, width in zip(out, spec.widths))


def encode(spec: RingSpec, value: Coord) -> int:
    assert len(value) == len(spec.widths)
    shift = 0
    out = 0
    for part, width in zip(value, spec.widths):
        assert 0 <= part < (1 << width)
        out |= part << shift
        shift += width
    return out


def decode(spec: RingSpec, index: int) -> Coord:
    assert 0 <= index < spec.cardinality
    out = []
    shift = 0
    for width in spec.widths:
        out.append((index >> shift) & ((1 << width) - 1))
        shift += width
    return tuple(out)


def _add_reductions(left: Reduction, right: Reduction,
                    coefficient: int = 1) -> Reduction:
    out = dict(left)
    for target, value in right.items():
        out[target] = out.get(target, 0) + coefficient * value
        if not out[target]:
            del out[target]
    return out


@lru_cache(maxsize=None)
def _reduce_split(a: int, b: int) -> Tuple[Tuple[int, int], ...]:
    """Reduce x^a y^b in Rsp, independently of the product table."""
    if a and b:
        return ()
    if a == b == 0:
        return ((0, 1),)
    exponent = a or b
    if exponent >= 5:
        return ()
    if exponent == 4:
        # x^4=2 and y^4=-2; these are equal in characteristic four, but the
        # signed presentation coefficient is retained here.
        return ((0, 2 if a else -2),)
    target = (1, 3, 5)[exponent - 1] if a else (2, 4, 6)[exponent - 1]
    return ((target, 1),)


@lru_cache(maxsize=None)
def _reduce_irreducible(a: int, b: int) -> Tuple[Tuple[int, int], ...]:
    """Reduce x^a y^b using y^2=-x^2-xy, x^4=0, x^3y=2."""
    if a >= 4:
        return ()
    if b >= 2:
        first = dict(_reduce_irreducible(a + 2, b - 2))
        second = dict(_reduce_irreducible(a + 1, b - 1))
        return tuple(sorted(_add_reductions(first, second, -1).items()))
    if b == 0:
        return (((0, 1, 3, 5)[a], 1),)
    if a == 3:
        return ((0, 2),)
    return (((2, 4, 6)[a], 1),)


def reduce_monomial(spec: RingSpec, a: int, b: int) -> Reduction:
    if spec.key == "split":
        return dict(_reduce_split(a, b))
    return dict(_reduce_irreducible(a, b))


def _basis_monomials(spec: RingSpec) -> Tuple[Tuple[int, int], ...]:
    if spec.key == "split":
        return ((0, 0), (1, 0), (0, 1), (2, 0), (0, 2), (3, 0), (0, 3))
    return ((0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (3, 0), (2, 1))


def presentation_mul(spec: RingSpec, left: Coord, right: Coord) -> Coord:
    """Second multiplier obtained by direct monomial reduction."""
    out = [0] * len(spec.widths)
    monomials = _basis_monomials(spec)
    for i, left_coefficient in enumerate(left):
        if not left_coefficient:
            continue
        for j, right_coefficient in enumerate(right):
            if not right_coefficient:
                continue
            a = monomials[i][0] + monomials[j][0]
            b = monomials[i][1] + monomials[j][1]
            for target, coefficient in reduce_monomial(spec, a, b).items():
                out[target] += left_coefficient * right_coefficient * coefficient
    return tuple(value % (1 << width) for value, width in zip(out, spec.widths))


def pow_element(spec: RingSpec, value: Coord, exponent: int) -> Coord:
    out = one(spec)
    for _ in range(exponent):
        out = mul(spec, out, value)
    return out


def additive_span(spec: RingSpec, generators: Iterable[int],
                  add_table: Sequence[Sequence[int]]) -> set[int]:
    span = {0}
    for generator in sorted(set(generators)):
        while True:
            enlarged = span | {add_table[value][generator] for value in span}
            if enlarged == span:
                break
            span = enlarged
    return span


def _sum_indices(spec: RingSpec, values: Iterable[int],
                 add_table: Sequence[Sequence[int]]) -> int:
    out = 0
    for value in values:
        out = add_table[out][value]
    return out


def gate_ring(spec: RingSpec, verbose: bool = True) -> dict:
    """Build and rigorously gate the full 256-element ring tables."""
    assert spec.cardinality == 256
    coords = [decode(spec, index) for index in range(spec.cardinality)]
    assert len(set(coords)) == 256
    assert all(encode(spec, value) == index for index, value in enumerate(coords))

    add_table = [[0] * 256 for _ in range(256)]
    mul_table = [[0] * 256 for _ in range(256)]
    for i, left in enumerate(coords):
        for j, right in enumerate(coords):
            sum_coord = add(spec, left, right)
            product_coord = mul(spec, left, right)
            assert product_coord == presentation_mul(spec, left, right), (
                spec.key, i, j, product_coord, presentation_mul(spec, left, right)
            )
            add_table[i][j] = encode(spec, sum_coord)
            mul_table[i][j] = encode(spec, product_coord)

    zero_index = encode(spec, zero(spec))
    one_index = encode(spec, one(spec))
    two_index = encode(spec, two(spec))
    assert zero_index == 0
    for i, value in enumerate(coords):
        assert add_table[i][zero_index] == i == add_table[zero_index][i]
        assert mul_table[i][one_index] == i == mul_table[one_index][i]
        assert mul_table[i][zero_index] == zero_index
        assert add_table[i][encode(spec, neg(spec, value))] == zero_index
        for j in range(256):
            assert add_table[i][j] == add_table[j][i]
            assert mul_table[i][j] == mul_table[j][i]

    # Bilinearity and associativity need only be checked on additive cyclic
    # generators after the exhaustive table/presentation cross-check.
    additive_generators = [one_index] + [encode(
        spec, tuple(1 if i == j else 0 for i in range(len(spec.widths)))
    ) for j in range(1, len(spec.widths))]
    for a in additive_generators:
        for b in additive_generators:
            for c in additive_generators:
                assert mul_table[mul_table[a][b]][c] == mul_table[a][mul_table[b][c]]
                assert mul_table[a][add_table[b][c]] == add_table[mul_table[a][b]][mul_table[a][c]]

    x_index = encode(spec, (0, 1, 0, 0, 0, 0, 0))
    y_index = encode(spec, (0, 0, 1, 0, 0, 0, 0))
    x2_index = mul_table[x_index][x_index]
    xy_index = mul_table[x_index][y_index]
    y2_index = mul_table[y_index][y_index]
    if spec.key == "split":
        assert xy_index == zero_index
        x4_index = encode(spec, pow_element(spec, coords[x_index], 4))
        y4_index = encode(spec, pow_element(spec, coords[y_index], 4))
        assert add_table[x4_index][y4_index] == zero_index
        assert x4_index == two_index
    else:
        assert _sum_indices(spec, (x2_index, xy_index, y2_index), add_table) == zero_index
        assert encode(spec, pow_element(spec, coords[x_index], 4)) == zero_index
        x3_index = mul_table[x2_index][x_index]
        assert mul_table[x3_index][y_index] == two_index

    # The residue map is the parity of the unit coordinate.  Its kernel is
    # the unique maximal ideal, and powers give the requested Hilbert vector.
    maximal = {i for i, value in enumerate(coords) if value[0] % 2 == 0}
    units = set(range(256)) - maximal
    assert len(maximal) == len(units) == 128
    for i in range(256):
        for j in range(256):
            assert ((coords[add_table[i][j]][0] & 1) ==
                    ((coords[i][0] ^ coords[j][0]) & 1))
            assert ((coords[mul_table[i][j]][0] & 1) ==
                    ((coords[i][0] & coords[j][0]) & 1))
    assert all(any(mul_table[u][v] == one_index for v in range(256)) for u in units)

    powers = [maximal]
    while powers[-1] != {zero_index}:
        products = {mul_table[a][b] for a in powers[-1] for b in maximal}
        powers.append(additive_span(spec, products, add_table))
        assert len(powers) <= 8
    power_sizes = tuple(len(part) for part in powers)
    assert power_sizes == (128, 32, 8, 2, 1), power_sizes
    hilbert = (1,) + tuple(
        (len(powers[i]).bit_length() - 1) -
        (len(powers[i + 1]).bit_length() - 1)
        for i in range(len(powers) - 1)
    )
    assert hilbert == (1, 2, 2, 2, 1)

    socle = {a for a in maximal if all(mul_table[a][b] == zero_index for b in maximal)}
    assert socle == {zero_index, two_index}
    assert add_table[two_index][two_index] == zero_index
    assert two_index != zero_index

    # Kernel of Sym^2(m/m^2) -> m^2/m^3 in coordinates x^2,xy,y^2.
    degree_two_products = (x2_index, xy_index, y2_index)
    quadratic_kernel = []
    for mask in range(8):
        value = _sum_indices(
            spec, (degree_two_products[i] for i in range(3) if (mask >> i) & 1),
            add_table,
        )
        if value in powers[2]:  # m^3
            quadratic_kernel.append(tuple((mask >> i) & 1 for i in range(3)))
    assert quadratic_kernel == [(0, 0, 0), spec.quadratic_kernel]

    summary = {
        "key": spec.key,
        "ring": spec.name,
        "cardinality": 256,
        "residue_field": "F2",
        "characteristic": 4,
        "maximal_ideal_cardinality": 128,
        "maximal_ideal_power_cardinalities": power_sizes,
        "hilbert_function": hilbert,
        "socle": "{0,2}",
        "quadratic_kernel_x2_xy_y2": quadratic_kernel,
        "full_pair_entries_cross_checked": 256 * 256,
        "table_gate": "PASS",
    }
    if verbose:
        print(f"{spec.name}: full 256-element table gate PASS; "
              f"|m^i|={power_sizes}; H={hilbert}; quadratic={spec.quadratic_kernel}",
              flush=True)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ring", choices=("split", "irreducible", "all"), default="all")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    keys = ("split", "irreducible") if args.ring == "all" else (args.ring,)
    summaries = [gate_ring(ring_spec(key)) for key in keys]
    if args.output:
        args.output.write_text(json.dumps(summaries, indent=2) + "\n")
        print(f"wrote {args.output}", flush=True)


if __name__ == "__main__":
    main()
